#!/system/bin/sh
# _  __    _    ___ ____    _    ____  
#| |/ /   / \  |_ _/ ___|  / \  |  _ \ 
#| ' /   / _ \  | |\___ \ / _ \ | |_) |
#| . \  / ___ \ | | ___) / ___ \|  _ < 
#|_|\_\/_/   \_\___|____/_/   \_\_| \_\                                                       
#
loge() { printf "\033[0;31m%s\033[0m\n" "$1"; }
logi() { printf "\033[0;32m%s\033[0m\n" "$1"; }
logw() { printf "\033[0;33m%s\033[0m\n" "$1"; }

tsh() {
    if [ "$(su -c id -u)" -eq 0 ]; then
        # Make the termux debugable
        su -c "sed -i 's/\\(com\\.termux [0-9][0-9]* \\)0/\\11/' /data/system/packages.list"
        # shellcheck disable=SC2016
        run-as com.termux files/usr/bin/bash -c 'export PATH=/data/data/com.termux/files/usr/bin:$PATH; export LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so; bash -i'
    else
        logw "su permission denyed"
    fi
}

logi "tsh command installed to current shell session."